-- Professional clip quality layer. SQLite stores Prisma enum values as TEXT.
ALTER TABLE "ClipCandidate" ADD COLUMN "hookScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "hookType" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "hookProblem" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "suggestedStartAdjustment" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "hookReason" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "emotionalWeightScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "ministryValueScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "socialShareabilityScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "visualConfidenceScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "speakerVisiblePercentage" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "averageTrackingConfidence" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "cropStabilityScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "wrongPersonSwitchRisk" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "majorCropJumpCount" INTEGER;
ALTER TABLE "ClipCandidate" ADD COLUMN "faceOrBodyDetectionCoverage" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "visualQualityScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "audioQualityScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "averageLoudness" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "peakLoudness" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "silenceAtBeginningSeconds" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "silenceAtEndSeconds" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "audioWarnings" JSONB;
ALTER TABLE "ClipCandidate" ADD COLUMN "captionQualityScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "captionQualityWarnings" JSONB;
ALTER TABLE "ClipCandidate" ADD COLUMN "arcCompletenessScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "finalQualityScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "qualityLabel" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "qualityReasons" JSONB;
ALTER TABLE "ClipCandidate" ADD COLUMN "rankingCategory" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "clipArcType" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "arcSummary" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "setupStartTime" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "mainPointTime" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "payoffTime" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "applicationTime" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "whyThisClipFeelsComplete" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "whatContextMightBeMissing" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "durationQualityScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "durationQualityLabel" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "bestPlatform" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "duplicateOfClipId" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "dedupeReason" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "dedupeScore" REAL;
ALTER TABLE "ClipCandidate" ADD COLUMN "postReadyStatus" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "postReadyReasons" JSONB;
ALTER TABLE "ClipCandidate" ADD COLUMN "postReadyBlockers" JSONB;
ALTER TABLE "ClipCandidate" ADD COLUMN "recommendedNextAction" TEXT;
ALTER TABLE "ClipCandidate" ADD COLUMN "manualCropRecommended" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ClipCandidate" ADD COLUMN "rawAiCandidate" JSONB;
ALTER TABLE "ClipCandidate" ADD COLUMN "qualityDebugSnapshot" JSONB;
ALTER TABLE "ProcessingJob" ADD COLUMN "generationSummary" JSONB;

CREATE INDEX "ClipCandidate_qualityLabel_idx" ON "ClipCandidate"("qualityLabel");
CREATE INDEX "ClipCandidate_finalQualityScore_idx" ON "ClipCandidate"("finalQualityScore");
CREATE INDEX "ClipCandidate_rankingCategory_idx" ON "ClipCandidate"("rankingCategory");
CREATE INDEX "ClipCandidate_postReadyStatus_idx" ON "ClipCandidate"("postReadyStatus");
